server:
  port: 8003

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

website:
  domain-name: www.sn.com

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl